### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by westurner** [codelabels/codelabels#1]
- [ ] #5 codelabels data model
  - [ ] Project
  - [ ] CodelabelSet
  - [ ] Codelabel
  - [ ] JSONLD
    - Python
      - https://github.com/kennethreitz/tablib
    - JS
      - https://github.com/digitalbazaar/jsonld.js
      - https://github.com/comunica/comunica
      - https://github.com/rdf-ext/rdf-ext#modules
      - https://github.com/linkeddata/rdflib.js
      - https://github.com/simplerdf/simplerdf
  - [ ] YAMLLD
- [ ] #2 STORY: users can configure GitHub project labels with codelabels from the CLI
- [ ] ENH: iterable(abbrev, label, bkg color, text color, dest) > codelabels.json|.yaml > {github, gitlab} issues api links are in #2 
  - [ ] is there an optimal input sequence for ordered sets of labels? sorted | sort order
- [ ] #3 STORY: users can learn about codelabels
  - [ ] ENH: generate HTML + RST

References:
- https://westurner.org/wiki/workflow#code-labels
- https://westurner.org/wiki/contributions#code-labels
- https://wrdrd.github.io/docs/consulting/software-development#codelabels
- 
- Labels: https://github.com/westurner/dotfiles/labels

**Comment by westurner** [comment]
See: https://github.com/westurner/wiki/issues/11
